name: openauth
description: A beautiful, secure and simple authenticator app that supports multiple protocols and services.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_secure_storage: ^5.0.2
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  settings_ui: ^2.0.2
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  get_it: ^7.2.0
  path_provider: ^2.0.11
  provider: ^6.0.3
  animations: ^2.0.3
  qr_code_scanner: ^1.0.0
  otp: ^3.0.4
  reorderables: ^0.5.0
  base32: ^2.1.3
  package_info_plus: ^1.4.2
  flutter_svg: ^1.1.0
  flutter_custom_tabs: ^1.0.4
  simple_icons: ^7.1.0
  file_picker: ^4.6.1
  introduction_screen: ^3.0.2
  url_launcher: ^6.1.3
  encrypt: ^5.0.1

dependency_overrides:
  platform: ^3.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.1
  build_runner: ^2.1.5

flutter:

  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: 'Rubik'
      fonts:
        - asset: 'fonts/Rubik-Bold.ttf'
          weight: 700
        - asset: 'fonts/Rubik-SemiBold.ttf'
          weight: 600
        - asset: 'fonts/Rubik-Medium.ttf'
          weight: 500
        - asset: 'fonts/Rubik-Regular.ttf'
          weight: 400
        - asset: 'fonts/Rubik-Light.ttf'
          weight: 300
  assets:
      - assets/vault.svg
      - assets/secure-login.svg
          
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
