name: CI
on: 
  push:
    branches: [master]
    paths-ignore: 
      - '**/README.md'
  pull-request:
    branches: [master]

  workflow_dispatch:

jobs:
  build: 
    name: flutter build
    runs_on: ubuntu-latest
    env: 
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.5.3"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: $
      - uses: subosito/flutter-actions@v1
        with:
          flutter-version: $
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test